"""Contracts for saved, combined customer estimates."""
from __future__ import annotations

from datetime import date, timedelta
from typing import Any, Literal, Optional
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field

from api.schemas.doors import DoorOpeningSpec
from api.schemas.quote import CommercialSettings, QuoteLineInput


EstimateStatus = Literal["draft", "priced", "finalized", "sent", "viewed", "accepted", "lost"]
# Once finalized, an estimate is a customer document: edits go into a revision.
LOCKED_STATUSES = {"finalized", "sent", "viewed", "accepted", "lost"}


def _today() -> date:
    return date.today()


def _valid_until() -> date:
    return date.today() + timedelta(days=30)


WindowOperation = Literal[
    "fixed", "casement", "awning", "single_slider", "double_slider", "single_hung", "double_hung"
]
WindowHanding = Literal["left", "right", "top"]
WindowElevation = Literal["front", "right", "left", "back", "other"]


class WindowSection(BaseModel):
    """One lite of a window, left to right as viewed from outside."""

    operation: WindowOperation
    # casement: hinge side; awning: "top"; single slider: operating sash side.
    handing: Optional[WindowHanding] = None


class WindowScreen(BaseModel):
    frame_colour: Optional[str] = None
    mesh_colour: Optional[str] = None


class WindowDetails(BaseModel):
    """Order-checklist details that do not affect the price.

    Kept outside ``spec`` on purpose: the pricing engine turns screen/hardware
    keys inside a spec into review items, and the pricing hash only covers
    ``id`` + ``spec``.
    """

    model_config = ConfigDict(extra="allow")

    tag: Optional[str] = None
    elevation: Optional[WindowElevation] = None
    # One entry per lite, in the same order as spec.lites (one entry for a
    # single window).
    sections: Optional[list[WindowSection]] = None
    # None means no screen.
    screen: Optional[WindowScreen] = None
    hardware: Optional[str] = None
    spacer: Optional[str] = None
    jamb_finish: Optional[str] = None
    notes: Optional[str] = None


class CustomerWindowLine(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid4()))
    location: str = ""
    description: str = ""
    spec: QuoteLineInput
    # Presentation-only order details; never sent to the pricing engine.
    details: Optional[WindowDetails] = None


class CustomerDoorOpening(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid4()))
    location: str = ""
    description: str = ""
    spec: DoorOpeningSpec


class EstimateAdder(BaseModel):
    """A job item on an estimate: a catalog adder or a one-off custom item."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    adder_id: Optional[str] = None
    custom: bool = False
    name: str = ""
    cost: float = Field(default=0.0, ge=0)
    price: float = Field(default=0.0, ge=0)
    # None = automatic quantity from the adder's unit (per window, per job...)
    qty: Optional[float] = Field(default=None, ge=0)
    note: str = ""


class TierOverrides(BaseModel):
    glazing: dict[str, Any] = Field(default_factory=dict)
    colour_ext: Optional[str] = None
    colour_int: Optional[str] = None


class EstimateTier(BaseModel):
    """A Good / Better / Best option: the same scope with product upgrades."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    name: str = "Option"
    description: str = ""
    window_overrides: TierOverrides = Field(default_factory=TierOverrides)


class CustomerEstimateDraft(BaseModel):
    customer_name: str = ""
    company_name: str = ""
    email: str = ""
    phone: str = ""
    project_name: str = ""
    project_address: str = ""
    salesperson: str = ""
    estimate_date: date = Field(default_factory=_today)
    valid_until: date = Field(default_factory=_valid_until)
    description: str = ""
    notes: str = ""
    terms: str = (
        "This estimate is based on the information available at the time of quoting. "
        "Final measurements, site conditions, product availability, and installation details "
        "will be confirmed before ordering."
    )
    windows: list[CustomerWindowLine] = Field(default_factory=list)
    doors: list[CustomerDoorOpening] = Field(default_factory=list)
    commercial: CommercialSettings = Field(default_factory=CommercialSettings)
    province: str = "ON"
    adders: list[EstimateAdder] = Field(default_factory=list)
    tiers: list[EstimateTier] = Field(default_factory=list)
    selected_tier: Optional[str] = None
    follow_up_on: Optional[date] = None
    # Set by the CRM when it starts a project from an opportunity. An update
    # that leaves them out keeps the existing link.
    crm_opportunity_id: Optional[str] = Field(default=None, max_length=64)
    crm_contact_id: Optional[str] = Field(default=None, max_length=64)


class CustomerEstimateLineAppend(BaseModel):
    """Product lines generated by a quote builder and assigned to a project."""

    windows: list[CustomerWindowLine] = Field(default_factory=list)
    doors: list[CustomerDoorOpening] = Field(default_factory=list)
    commercial: Optional[CommercialSettings] = None


class CustomerEstimateResponse(CustomerEstimateDraft):
    id: str
    estimate_number: Optional[str] = None
    status: EstimateStatus
    pricing: Optional[dict[str, Any]] = None
    pricing_hash: Optional[str] = None
    created_at: str
    updated_at: str
    finalized_at: Optional[str] = None
    sent_at: Optional[str] = None
    viewed_at: Optional[str] = None
    accepted_at: Optional[str] = None
    acceptance: Optional[dict[str, Any]] = None
    lost_at: Optional[str] = None
    lost_reason: Optional[str] = None
    public_token: Optional[str] = None
    revision_of: Optional[str] = None
    revision_number: int = 1
    deleted_at: Optional[str] = None


class CustomerEstimateSummary(BaseModel):
    id: str
    estimate_number: Optional[str] = None
    status: EstimateStatus
    customer_name: str = ""
    company_name: str = ""
    project_name: str = ""
    salesperson: str = ""
    total: Optional[float] = None
    margin_percent: Optional[float] = None
    updated_at: str
    finalized_at: Optional[str] = None
    sent_at: Optional[str] = None
    follow_up_on: Optional[date] = None
    revision_number: int = 1
    deleted_at: Optional[str] = None
    crm_opportunity_id: Optional[str] = None


class CrmLinkRequest(BaseModel):
    """The CRM opportunity/contact a project belongs to, set when the CRM adds its customer."""

    crm_opportunity_id: str = Field(min_length=1, max_length=64)
    crm_contact_id: Optional[str] = Field(default=None, max_length=64)


class SendEstimateRequest(BaseModel):
    to: str = ""
    cc: str = ""
    message: str = ""
    # The app's public origin, used to build the customer's link.
    portal_base_url: str = ""


class LostRequest(BaseModel):
    reason: str = Field(min_length=1)


class FollowUpRequest(BaseModel):
    follow_up_on: Optional[date] = None
    note: str = ""


class AcceptEstimateRequest(BaseModel):
    name: str = Field(min_length=2, max_length=200)
    signature: str = Field(min_length=20, max_length=400_000)
    tier_id: Optional[str] = None
    accepted_terms: bool

