"""Contracts for saved, combined customer estimates."""
from __future__ import annotations

from datetime import date, timedelta
from typing import Any, Literal, Optional
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field

from api.schemas.doors import DoorOpeningSpec
from api.schemas.quote import CommercialSettings, QuoteLineInput


EstimateStatus = Literal["draft", "priced", "finalized"]


def _today() -> date:
    return date.today()


def _valid_until() -> date:
    return date.today() + timedelta(days=30)


WindowOperation = Literal[
    "fixed", "casement", "awning", "single_slider", "double_slider", "single_hung", "double_hung"
]
WindowHanding = Literal["left", "right", "top"]
WindowElevation = Literal["front", "right", "left", "back", "other"]


class WindowSection(BaseModel):
    """One lite of a window, left to right as viewed from outside."""

    operation: WindowOperation
    # casement: hinge side; awning: "top"; single slider: operating sash side.
    handing: Optional[WindowHanding] = None


class WindowScreen(BaseModel):
    frame_colour: Optional[str] = None
    mesh_colour: Optional[str] = None


class WindowDetails(BaseModel):
    """Order-checklist details that do not affect the price.

    Kept outside ``spec`` on purpose: the pricing engine turns screen/hardware
    keys inside a spec into review items, and the pricing hash only covers
    ``id`` + ``spec``.
    """

    model_config = ConfigDict(extra="allow")

    tag: Optional[str] = None
    elevation: Optional[WindowElevation] = None
    # One entry per lite, in the same order as spec.lites (one entry for a
    # single window).
    sections: Optional[list[WindowSection]] = None
    # None means no screen.
    screen: Optional[WindowScreen] = None
    hardware: Optional[str] = None
    spacer: Optional[str] = None
    jamb_finish: Optional[str] = None
    notes: Optional[str] = None


class CustomerWindowLine(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid4()))
    location: str = ""
    description: str = ""
    spec: QuoteLineInput
    # Presentation-only order details; never sent to the pricing engine.
    details: Optional[WindowDetails] = None


class CustomerDoorOpening(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid4()))
    location: str = ""
    description: str = ""
    spec: DoorOpeningSpec


class CustomerEstimateDraft(BaseModel):
    customer_name: str = ""
    company_name: str = ""
    email: str = ""
    phone: str = ""
    project_name: str = ""
    project_address: str = ""
    salesperson: str = ""
    estimate_date: date = Field(default_factory=_today)
    valid_until: date = Field(default_factory=_valid_until)
    description: str = ""
    notes: str = ""
    terms: str = (
        "This estimate is based on the information available at the time of quoting. "
        "Final measurements, site conditions, product availability, and installation details "
        "will be confirmed before ordering."
    )
    windows: list[CustomerWindowLine] = Field(default_factory=list)
    doors: list[CustomerDoorOpening] = Field(default_factory=list)
    commercial: CommercialSettings = Field(default_factory=CommercialSettings)


class CustomerEstimateLineAppend(BaseModel):
    """Product lines generated by a quote builder and assigned to a project."""

    windows: list[CustomerWindowLine] = Field(default_factory=list)
    doors: list[CustomerDoorOpening] = Field(default_factory=list)
    commercial: Optional[CommercialSettings] = None


class CustomerEstimateResponse(CustomerEstimateDraft):
    id: str
    estimate_number: Optional[str] = None
    status: EstimateStatus
    pricing: Optional[dict[str, Any]] = None
    pricing_hash: Optional[str] = None
    created_at: str
    updated_at: str
    finalized_at: Optional[str] = None


class CustomerEstimateSummary(BaseModel):
    id: str
    estimate_number: Optional[str] = None
    status: EstimateStatus
    customer_name: str = ""
    company_name: str = ""
    project_name: str = ""
    total: Optional[float] = None
    updated_at: str
    finalized_at: Optional[str] = None

